title: "My Blog"
description: "A blog powered by Jekyll and GitHub Pages"
baseurl: "" # Leave empty for user/organization site, set to /repo-name for project site
url: "https://wschleif.github.io/HackTheBox" # Your repository URL
theme: minima
